-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [barrett]: function definitions
import Aeneas
import Barrett.Types
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

namespace barrett

/- [barrett::BARRETT_SHIFT]
   Source: 'src/lib.rs', lines 5:0-5:30 -/
@[global_simps, irreducible] def BARRETT_SHIFT : Std.I64 := 26#i64

/- [barrett::BARRETT_R]
   Source: 'src/lib.rs', lines 6:0-6:33 -/
@[global_simps, irreducible] def BARRETT_R : Std.I64 := 67108864#i64

/- [barrett::BARRETT_MULTIPLIER]
   Source: 'src/lib.rs', lines 9:0-9:38 -/
@[global_simps, irreducible] def BARRETT_MULTIPLIER : Std.I64 := 20159#i64

/- [barrett::FIELD_MODULUS]
   Source: 'src/lib.rs', lines 11:0-11:43 -/
@[global_simps, irreducible] def FIELD_MODULUS : Std.I32 := 3329#i32

/- [barrett::barrett_reduce]:
   Source: 'src/lib.rs', lines 28:0-43:1 -/
def barrett_reduce (value : Std.I32) : Result Std.I32 := do
  let i ← lift (core.convert.num.FromI64I32.from value)
  let t ← i * BARRETT_MULTIPLIER
  let i1 ← BARRETT_R >>> 1#i32
  let t1 ← t + i1
  let quotient ← t1 >>> BARRETT_SHIFT
  let quotient1 ← lift (IScalar.cast .I32 quotient)
  let sub ← quotient1 * FIELD_MODULUS
  value - sub

end barrett
